// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetCareAPI.Data;

#nullable disable

namespace VetCareAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119165605_add_photo_to_clinic")]
    partial class add_photo_to_clinic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VetCareAPI.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "Role IN ('Admin','ClinicStaff','User')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Email = "admin@gmail.com",
                            FullName = "System Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEFBlcphBR2VdzREjobOqd+lyX079u33WlqzjAnURuM/kwQlKCpy2wZ9nsLSK4blkvg==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "owner@gmail.com",
                            FullName = "Demo Owner",
                            PasswordHash = "AQAAAAIAAYagAAAAEL2Z/MDnmseAtqaj5Rvr/0HSykjkIuh/D5b5aHUdn1yiqNI9BUHoCxlUZYhA2eInBw==",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "staff@gmail.com",
                            FullName = "Kaunas Vet Staff",
                            PasswordHash = "AQAAAAIAAYagAAAAEP3ggSAiRexQx1Oe6+uWxRHVlvNEsJ1YMv+Ma9M3WL5HujKS3pVHg1OBJ9GKMGrtyA==",
                            Role = "ClinicStaff"
                        });
                });

            modelBuilder.Entity("VetCareAPI.Models.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Laisvės al. 1",
                            City = "Kaunas",
                            Name = "ZooVet Kaunas",
                            Phone = "+37060000001"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222222"),
                            Address = "Gedimino pr. 2",
                            City = "Vilnius",
                            Name = "VetHelp Vilnius",
                            Phone = "+37060000002"
                        });
                });

            modelBuilder.Entity("VetCareAPI.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111111"),
                            DateOfBirth = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maksis",
                            Species = "Dog",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-222222222222"),
                            DateOfBirth = new DateTime(2021, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Murka",
                            Species = "Cat",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DateOfBirth = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pūkis",
                            Species = "Rabbit",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("VetCareAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Device")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VetCareAPI.Models.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DiagnosisCode")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosisText")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Severity")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("PetId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-111111111111"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndsAt = new DateTime(2025, 9, 15, 9, 30, 0, 0, DateTimeKind.Utc),
                            Notes = "Vaccination completed.",
                            PetId = new Guid("33333333-3333-3333-3333-111111111111"),
                            Reason = "Vaccination",
                            Severity = "Mild",
                            StartsAt = new DateTime(2025, 9, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-222222222222"),
                            ChiefComplaint = "Limping on right hind leg",
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndsAt = new DateTime(2025, 10, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Annual check.",
                            PetId = new Guid("33333333-3333-3333-3333-111111111111"),
                            Reason = "Checkup",
                            Severity = "Moderate",
                            StartsAt = new DateTime(2025, 10, 12, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-333333333333"),
                            ChiefComplaint = "Bad breath",
                            ClinicId = new Guid("11111111-1111-1111-1111-222222222222"),
                            EndsAt = new DateTime(2025, 10, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Notes = "Dental check.",
                            PetId = new Guid("33333333-3333-3333-3333-222222222222"),
                            Reason = "Dental",
                            Severity = "Mild",
                            StartsAt = new DateTime(2025, 10, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChiefComplaint = "Loss of appetite",
                            ClinicId = new Guid("11111111-1111-1111-1111-222222222222"),
                            EndsAt = new DateTime(2025, 10, 5, 16, 30, 0, 0, DateTimeKind.Utc),
                            Notes = "Owner cancelled day before.",
                            PetId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Reason = "Illness",
                            Severity = "Moderate",
                            StartsAt = new DateTime(2025, 10, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("VetCareAPI.Models.AppUser", b =>
                {
                    b.HasOne("VetCareAPI.Models.Clinic", "Clinic")
                        .WithMany("Staff")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("VetCareAPI.Models.Pet", b =>
                {
                    b.HasOne("VetCareAPI.Models.AppUser", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VetCareAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("VetCareAPI.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VetCareAPI.Models.Visit", b =>
                {
                    b.HasOne("VetCareAPI.Models.Clinic", "Clinic")
                        .WithMany("Visits")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCareAPI.Models.Pet", "Pet")
                        .WithMany("Visits")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VetCareAPI.Models.AppUser", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("VetCareAPI.Models.Clinic", b =>
                {
                    b.Navigation("Staff");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("VetCareAPI.Models.Pet", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
